name: Generate documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate documentation
        uses: Sett17/gomarkdoc-action@v1.0.1
        with:
          output-file: DOCS.md

      - name: Commit documentation
        uses: EndBug/add-and-commit@v9
        with:
          commit: --signoff
          default_author: github_actor
          message: 'Update docs'